### PR TITLE
Change over to R package

### PR DESCRIPTION
**Pull request by daynefiler**
Hello all, 

Need some input here before merging this in. I propose we change the repo over to an R package (#1). This will allow the students to run `vignette("class1")` and have the vignette pulled up in RStudio. 

To see how it works:

    library(devtools)
    install_github("How-to-Learn-to-Code/rclass", ref = "issue-01", build_vignettes = TRUE)
    library(htltcR)
    vignette("class1")

### CODE REVIEW

**Comment by aeallen** [comment]
This worked for me once I ran

```devtools::install_github("rstudio/rmarkdown")
```
I think this works really nicely! How do you envision using this in the classroom?

**Comment by daynefiler** [comment]
When we taught students were either reading off printouts or having to constantly switch back and forth between the html documents and their RStudio window. This simplifies the process for students allowing them to follow along in RStudio.

**Comment by daynefiler** [comment]
This also adds the datasets into the package, allowing them to be called simply by `data`. This makes writing examples/lectures easier and ensures all files will compile across platforms.

**Comment by daynefiler** [comment]
Then the only file distribution we need to do is having the students run the `install_github` at the beginning of class.

**Comment by aeallen** [comment]
That sounds like a good plan to me. Thanks for putting this all together!

**Pull request merged**
