### PR TITLE
Closes #6: New IO class

### LINKED ISSUE #6: Break plotting and IO into two vignettes
Data IO should probably go before plotting in the sequence. Breaking these out will make different approaches to plotting lectures easier.

### PR DESCRIPTION
**Pull request by daynefiler**
This commit gives a new IO vignette, incorporating
the vignette from #10 as an exercise. The rmd from
#10 was moved to the hwsolutions folder as a
reference to instructors. It contains extensive use
of dplyr, so it may not be appropriate for students.

The crime.xls and crime.csv files were added to
have a static copy, shorten the urls, and provide
the students the "goal" for the exercise.

More could be done to flesh out saving R objects.

The section about connections could easily be
skipped.

### CODE REVIEW

**Comment by daynefiler** [comment]
This will also close #10.

**Comment by aeallen** [comment]
This looks good to me. I'm not going to merge until we have @snystrom 's thoughts as well.

**Comment by snystrom** [comment]
I'm fine with that change. I agree that perhaps some of the connections stuff could be shortened. Maybe I missed it but there doesn't seem to be a discussion of `stringsAsFactors` (and why it should be `FALSE` most times) which I think is one of the most important parts of data import, especially if using base import functions.

**Comment by daynefiler** [comment]
I left the `stringsAsFactors` as an exercise. It's setup by the last examples. We can move it to being explicitly defined if you think that would be better.

**Comment by daynefiler** [comment]
We explicitly ignore factors in the class, so it should be addressed (whether in the exercise or in the class notes)

**Comment by snystrom** [comment]
Factors are ignored in the whole HLC curriculum? That seems like an oversight.

Regardless, I think it's worth noting to students that you almost always need to set `stringsAsFactors = F` during import of real data.

**Comment by daynefiler** [comment]
They are currently ignored throughout the curriculum. My thought is that they're sort of complicated to use and R-specific. I only use factors when I'm building complicated linear models.

**Comment by daynefiler** [comment]
(even your comment suggests one should basically never use factors!)

**Comment by snystrom** [comment]
In many ways this comes back to the philosophical question of whether this is a programming course or an R course, which is a discussion that is too big to have now (or at least in this PR). 

I see no reason not to merge this.

**Comment by snystrom** [comment]
You shouldn't use factors as default, which is why I think `stringsAsFactors` needs a mention. Especially since it can cause weird issues later on since R sees them as numbers, it could throw beginners for a loop when they get to trying stuff with their own data.

**Comment by aeallen** [comment]
I think we all agree that factors shouldn't be the default. Let's add something in the notes about it, because I think it might confuse some students if we just mention it in the assignments. I also don't want people who don't do the homework to miss that piece of information.

**Comment by daynefiler** [comment]
Updated.

**Pull request merged**
