### PR TITLE
Issue #37 Updated learning objectives and added some in class exercises

### PR DESCRIPTION
**Pull request by aeallen**
#37 

More in-class exercises would be ideal, but this is a start.

Learning objectives were updated to be more easy to assess.

### CODE REVIEW

**Comment by daynefiler** [comment]
Sorry I haven't responded sooner. I would like to leave in the control stuff that you took out. Also, it looks like you changed one of the titles? Did you want to change all of them? We should update the name of the package, if so.

**Comment by daynefiler** [comment]
I will add another commit today. Going to make sure the new code you added is in line with the Google style guide.

**Comment by aeallen** [comment]
Changing all the names sounds like a hassle. I was trying to rebrand to HLC because it is less of a mouthful, but we can leave it as HtLtC.

**Comment by daynefiler** [comment]
Yea, a rebrand would be nice haha.

**Comment by daynefiler** [comment]
Closes #37

**Pull request merged**
