### PR TITLE
Issue 21 - ggplot lesson

### PR DESCRIPTION
**Pull request by mbergins**
I've converted the yeast data set into tidy format and written up a lesson using ggplot to build up a few plots.

### CODE REVIEW

**Comment by daynefiler** [comment]
Hi Matt, how can I be helpful here?

**Comment by mbergins** [comment]
This is the re-working of the plotting lesson into ggplot that I mentioned in the meeting we had a few weeks ago about the R curriculum. I thought we were using pull requests associated with issues to bring new lessons into the system. So I suppose I hoping someone else can take a look at this and approve adding the new lesson to the system.

**Comment by daynefiler** [comment]
Sounds good I will take a look and provide any feedback I can with the caveat that I am not a ggplot user.

**Comment by daynefiler** [comment]
Hi Matt, take a look. I think it's ready for merging. I removed the csv and added a data object to the package. The I/O lecture comes first, so I don't think it's needed there.

**Comment by daynefiler** [comment]
I did a quick merge from the current master and updated the DESCRIPTION to take care of any merge issues.

**Comment by mbergins** [comment]
I'm getting an error when I run devtools::check on this branch, one was related to the line break in Suggests. This last push removes the line break. Maybe this is a recent R package change?

Either way, I was able to install the package from this branch, so I think we good to go for merge.

**Comment by mbergins** [comment]
Also, all your edits look good to me, thanks for cleaning up the style.

**Comment by daynefiler** [comment]
Shoot! I forgot to check that. I wasn't sure how line breaks worked in the DESCRIPTION file. Thanks for fixing it!

**Comment by daynefiler** [comment]
Closes #21

**Pull request merged**
